---
engines:
  bundler-audit:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-60
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- spec/
