AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4.2

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FormatStringToken:
  Exclude:
    - 'lib/date_range_formatter.rb'

Lint/UnifiedInteger:
  Exclude:
    - 'lib/fixnum.rb'
    - 'spec/fixnum_spec.rb'
