AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4.2

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FormatStringToken:
  Exclude:
    - 'lib/date_range_formatter.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/date_range_formatter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/date_range_formatter.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/date_range_formatter.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/date_range_formatter.rb'

Style/IfInsideElse:
  Exclude:
    - 'lib/date_range_formatter.rb'
