AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.1

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FormatStringToken:
  Exclude:
    - 'lib/date_range_formatter.rb'
